### ISSUE TITLE
problem running bandits_tutorial.ipynb

### ISSUE THREAD

**Issue by XiaomingY** [tensorflow/agents#414] opened 2020-07-04 14:04 UTC
Under session "Training an Agent", I got the following error

> TypeError: Tensor dtypes do not match spec dtypes:
Trajectory(step_type=tf.int32, observation=tf.int64, action=tf.int32, policy_info=(), next_step_type=tf.int32, reward=tf.float32, discount=tf.float32)
vs.
Trajectory(step_type=tf.int32, observation=tf.int32, action=tf.int32, policy_info=(), next_step_type=tf.int32, reward=tf.float32, discount=tf.float32)

I am very new to tf-agent and still trying to understand the basics. I also find something confusing in the policy session:
observation is defined as int32 
> observation_spec = tensor_spec.BoundedTensorSpec(
        shape=(1,), dtype=tf.int32, minimum=-2, maximum=2)

but when its type is printed
> print (current_time_step.observation)

it still shows int64
>Observation:
tf.Tensor([[2]], shape=(1, 1), dtype=int64)
Action:
tf.Tensor([2], shape=(1,), dtype=int32)
Reward:
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)

Could this be related to the above dtypes mismatch error?

**Comment by bartokg** [comment] 2020-08-20 08:26
Hi,
Sorry for the late response.
I just ran the tutorial, and for me it runs without any error. The printout shows the observation is of type int32. Do you still face the issue? Can you explain how to reproduce the error?

**Comment by tfboyd** [comment] 2020-11-09 17:08
We now run these notebooks every night for validation. Closing as the issue is old. If you are still having an issue please provide the error and repro information.  I realized it has been many many months. So it either worked or you moved on. I hope it just worked and you found what you needed or wanted.

**Closed as completed by tfboyd** 2020-11-09 17:08 UTC
Labels: bandits
