### ISSUE TITLE
how to print log_probability in tf agents

### ISSUE THREAD

**Issue by marcelyz** [tensorflow/agents#157] opened 2019-07-10 02:47 UTC
Hi, I have set emit_log_probability=True, but it error when I want to run the demo of 21 game, so how to get the action_step.info on log_probability?
<img width="1271" alt="屏幕快照 2019-07-10 上午10 44 24" src="https://user-images.githubusercontent.com/22769274/60936544-09211000-a300-11e9-9619-739c115e202e.png">

**Comment by kbanoop** [comment] 2019-09-10 20:34
It looks like only one of the structures has a non empty policy_info field. Hard to say exactly what the issue is without seeing the code, but my guess is that the specs used to construct the replay buffer did not have this field. 

Closing this for now, please re-open if you have more questions and add a code snippet as well.

**Closed as completed by kbanoop** 2019-09-10 20:34 UTC
