### ISSUE TITLE
DqnAgent.train throws error in TF2.0 environment as Adam.apply_gradients is called with parameter global_step

### ISSUE THREAD

**Issue by ideenfix** [tensorflow/agents#113] opened 2019-05-21 19:38 UTC

**Comment by samfishman** [comment] 2019-05-21 19:42
Hi ideenfix,

Can you please provide some more details about this issue? I am able to run agents/dqn/examples/v2/train_eval.py without an errors. Include your environment configuration (tensorflow version, tf-agents version, etc.) as well as the script you are running.

**Comment by ideenfix** [comment] 2019-05-21 19:44
First, i'm new in this community and don't know the exact rules of the game. Sorry for that

Currently, I'm developing an Agent to Play against the OpenAI Pong. DqnAgent throws an error in TF2.0 Environment as soon as e.g. Adam.apply_gradients is called with Parameter global_step. This Parameter isn't supported by TF2.0.0a0.

**Comment by samfishman** [comment] 2019-05-21 19:51
I'm not playing any games here, just trying to understand the issue.

As mentioned before, it's hard for me to debug this issue without more information about how to reproduce this. I would need more information, including a program/script that, when run, produces the error you mention and the versions of all the components you're using (tensorflow, tf_agents, etc.). Without that, we can't really help.

**Comment by ideenfix** [comment] 2019-05-21 19:52
Hi samfishman,

OS: Windows 10
Python: 3.7
I'm using a virtual Environment created by PyCharm. Attached the pip list report for this environment
[pytf2pip.txt](https://github.com/tensorflow/agents/files/3204226/pytf2pip.txt)

My script but not as .py 
[myscript.txt](https://github.com/tensorflow/agents/files/3204236/myscript.txt)

**Comment by ideenfix** [comment] 2019-05-21 19:57
In dqn_agent.py you can find in line 273 the following Code part
`    self._optimizer.apply_gradients(grads_and_vars,
                                    global_step=self.train_step_counter)
`

**Comment by samfishman** [comment] 2019-05-21 20:02
This script isn't runnable since I don't have access to the `lib` package
it imports. Please provide a self-contained script (e.g. one file) that
reproduces the error.

**Comment by sguada** [comment] 2019-05-21 20:04
I think the issue is that keras.optimizers don't take `global_step` in `apply_gradients`, while tf.optimizers do.

Can you try using `tf.compat.v1.train.AdamOptimizer` and see if that fix the problem, and then we will update the agent to work with keras.Optimizers

**Comment by ideenfix** [comment] 2019-05-21 20:19
@samfishman 

Attached the self-contained script:
[01_dqn_basic_tf_selfrunning.txt](https://github.com/tensorflow/agents/files/3204337/01_dqn_basic_tf_selfrunning.txt)

**Comment by ideenfix** [comment] 2019-05-21 20:29
@sguada:
This Optimizer runs.

**Comment by ideenfix** [comment] 2019-05-21 20:40
I have another issue after using parameter train_step_counter=

Here the Code snippet (according to colab example)
`    # dtype=tf.int64 muss sein, ansonsten Fehler beim Aufruf von tf_agent.train(experience)
    train_step_counter = tf.Variable(0)
    # train_step_counter = tf.Variable(0, dtype=tf.int64)

    # erzeugen und initialisieren des DQN - Agenten, verantwortlich für die Steuerung gemäß der DQN-Strategie
    tf_agent = dqn_agent.DqnAgent(
        train_env.time_step_spec(),
        train_env.action_spec(),
        q_network=net,
        optimizer=optimizer,
        epsilon_greedy=params["epsilon_final"],
        gamma=params['gamma'],
        td_errors_loss_fn=dqn_agent.element_wise_squared_loss,
        train_step_counter=train_step_counter
    )
`

After calling DqnAgent.train following error is thrown
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/git/Deep-Reinforcement-Learning-Hands-On/Chapter07/01_dqn_basic_tf.py", line 165, in <module>
    train_loss = tf_agent.train(experience)
  File "D:\pyenv\tf2\lib\site-packages\tf_agents\agents\tf_agent.py", line 177, in train
    loss_info = self._train_fn(experience=experience, weights=weights)
  File "D:\pyenv\tf2\lib\site-packages\tf_agents\agents\dqn\dqn_agent.py", line 256, in _train
    weights=weights)
  File "D:\pyenv\tf2\lib\site-packages\tf_agents\agents\dqn\dqn_agent.py", line 353, in loss
    name='loss', data=loss, step=self.train_step_counter)
  File "D:\pyenv\tf2\lib\site-packages\tensorboard\plugins\scalar\summary_v2.py", line 65, in scalar
    metadata=summary_metadata)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py", line 632, in write
    _should_record_summaries_v2(), record, _nothing, name="summary_cond")
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\framework\smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py", line 627, in record
    name=scope)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\ops\gen_summary_ops.py", line 793, in write_summary
    writer, step, tensor, tag, summary_metadata, name=name, ctx=_ctx)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\ops\gen_summary_ops.py", line 824, in write_summary_eager_fallback
    step = _ops.convert_to_tensor(step, _dtypes.int64)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 1108, in convert_to_tensor_v2
    as_ref=False)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1420, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "D:\pyenv\tf2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1371, in _dense_var_to_tensor
    "of type {!r}".format(dtype.name, self.dtype.name))
ValueError: Incompatible type conversion requested to type 'int64' for variable of type 'int32'

If you changed the initialization of this variable to 
    train_step_counter = tf.Variable(0, dtype=tf.int64)
then you have no Problems

Shall I open a new issue or is that ok?

**Comment by egonina** [comment] 2019-05-23 15:56
@ideenfix can you please file a new issue about the incompatible type with repro instructions (what you included here) so we can close this original issue you filed?

**Closed as completed by egonina** 2019-05-23 15:56 UTC

**Comment by sguada** [comment] 2019-05-23 17:52
So the variable used as  train_step should be an tf.int64

**Comment by tagomatech** [comment] 2019-10-22 22:22
> I think the issue is that keras.optimizers don't take `global_step` in `apply_gradients`, while tf.optimizers do.
> 
> Can you try using `tf.compat.v1.train.AdamOptimizer` and see if that fix the problem, and then we will update the agent to work with keras.Optimizers

Also following @ideenfix's comment, replacing: `self._optimizer.apply_gradients(grads_and_vars), global_step=self.train_step_counter) ` with: `self._optimizer.apply_gradients(grads_and_vars)`  in the file **dqn_agent.py** seems to solve the issue.

In fact, now using:
`optimizer = tf.optimizers.Adam(learning_rate=learning_rate)`  instead of: `optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)` in [1_dqn_tutorial.ipynb](https://github.com/tensorflow/agents/blob/master/tf_agents/colabs/1_dqn_tutorial.ipynb) works well.

Shall someone pull a request?

Thank you,
tagoma

**Comment by sguada** [comment] 2019-10-22 23:58
Sure
