### ISSUE TITLE
categorical_q_network.CategoricalQNetwork does not appear in the API docs

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [tensorflow/agents#541] opened 2021-01-18 07:52 UTC
Strangely, [categorical_q_network.CategoricalQNetwork](https://github.com/tensorflow/agents/blob/v0.6.0/tf_agents/networks/categorical_q_network.py) is nowhere to be found in the [API docs](https://www.tensorflow.org/agents/api_docs/python/tf_agents/networks) 0.6.0. I noticed it's not imported in `tf_agents/networks/`[`__init__.py`](https://github.com/tensorflow/agents/blob/v0.6.0/tf_agents/networks/__init__.py).

**Comment by tfboyd** [comment] 2021-01-20 16:33
I will ask and I think the two are related. My guess is because of the manual step to add it to init.py that it was missed. Maybe we missed some others. I also don't know why the explicity imports are in the init.py vs. just happen.

**Comment by tfboyd** [comment] 2021-01-20 18:49
Confirmed, this was just an oversight. I will push a commit and will **close this issue when tf-agents-nightly has the fix**. ETA ~48 hours just due to code reviews and such. I am also checking if we missed any other networks.  Thank you for the clear details and links. It we very easy to figure out what was wrong.

**Comment by WhistleWhileYouWork** [comment] 2021-01-20 18:58
Excellent! tf-agents is such a great resource, I'm glad to contribute (in my own small way).

Also, now that 0.7.1 is out, should the docs on [tensorflow.org](https://www.tensorflow.org/agents/api_docs/python/tf_agents) be updated to the new version? Although there is no direct indication of the API version on the website, the GitHub source linkbacks still point to the 0.6.0 version.

**Comment by tfboyd** [comment] 2021-01-20 19:04
@WhistleWhileYouWork  I will check on the links as well and keep this issue open until I am sure.  The API should be updated for 0.7.1. DevRel handles this and I am good friends with them so it is easy to figure out.  We had some weird stuff with TF 2.4 around the Holiday so it is worth a double check.  Thanks for the extra info. I am glade you like the tool.  FYI the new API is really nice and we have posted some much better README pages that will be the standard going forward. 

https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/examples/sac

https://github.com/tensorflow/agents/tree/master/tf_agents/experimental/examples/ppo

DQN tested with Atari Pong is next I just need to finish writing it up. These examples will replace the existing SAC/PPO very soon. We are just taking our time. The old style (api) is not being deprecated we just found this style to work better as detailed here:  https://github.com/tensorflow/agents/tree/master/tf_agents/train

**Comment by WhistleWhileYouWork** [comment] 2021-01-20 19:20
I love the examples you linked. Being able to see how each type of RL algo performs on different problems as well as being able to see how they are implemented and perform for the same problems (if applicable) is what will help adoption of `tf-agents`. You can never have too much usage examples. I think that's one of the TensorFlow project's best assets.

I wasn't aware of this new approach with the Actor-Learner API! I just started to wrap my head around the original API. This new approach looks interesting.  I can't wait to dive in. I will be very busy trying it out over the next couple days. Thanks!

**Comment by tfboyd** [comment] 2021-01-21 18:05
Communication over kill here:  Website is fixed to point back to 0.7.1 and the API should be updated for 0.7.1.  https://www.tensorflow.org/agents/api_docs/python/tf_agents.  It will not have the categorical_q_network. The CL/Commit for categorical_q_network should show up in tf-agents-nightly tonight/tomorrow.  I will confirm and then close this issue.  I also found that mask_splitter_network was missing so I added that as well.  

https://github.com/tensorflow/agents/commit/02222da09411d5c3e3adf602b14db84afbee88e7

**Comment by tfboyd** [comment] 2021-01-22 17:28
Alright I tested 

`from tf_agents.networks import categorical_q_network` after `pip install tf-agents-nightly[reverb]` and it looks good. And in the previous comment I verified the API docs are 0.7.1.  FYI the API documents will not show `categorical_q_network` until our next release which most likely will not occur until TF 2.5.  Closing as I think all issues in this issue are resolved.  Gotta love that.  Ping me if I missed something.

**Closed as completed by tfboyd** 2021-01-22 17:28 UTC

**Comment by WhistleWhileYouWork** [comment] 2021-02-01 21:53
@tfboyd Hi, I found two more missing Classes in the [**API**](https://www.tensorflow.org/agents/api_docs/python/tf_agents/specs): 
* tf_agents.specs.tensor_spec.BoundedTensorSpec
* tf_agents.specs.tensor_spec.TensorSpec

This time they _are_ imported in [**__init__.py**](https://github.com/tensorflow/agents/blob/r0.7.1/tf_agents/specs/__init__.py) however, unlike *ArraySpec, the *TensorSpec classes are just [**direct imports**](https://github.com/tensorflow/agents/blob/r0.7.1/tf_agents/specs/tensor_spec.py#L34-L35) from the `tf.TensorSpec` module.

**Comment by tfboyd** [comment] 2021-02-02 00:36
I just opened https://github.com/tensorflow/agents/issues/547  and made an internal bug.  I see what you mean.  I will need to ask around to see what is up as I don't have an idea at a glance.
