### ISSUE TITLE
metric_utils.eager_compute not evaluating "fast"

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/agents#360] opened 2020-05-02 12:18 UTC
When I first tried TF-Agents metric_utils.eager_compute would evaluate the eval_env very fast (Speeded up), which was very good. Unfortunately, now it has stopped doing so, it is now running at the same speed as the train_env. My colleagues have run the exact same code, at their eval_env Is speeded up. I have tried reinstalling Windows 10 pro x64, reinstalling drivers, reinstalling pycharm, rewrite the code, try to disable use_functions but with no luck. 

```
results = metric_utils.eager_compute(
                    eval_metrics,
                    eval_tf_env,
                    eval_policy,
                    num_episodes=num_eval_episodes,
                    train_step=global_step,
                    summary_writer=eval_summary_writer,
                    summary_prefix='Metrics',
                )
```
Hardware & OS:

- Windows 10 Pro x64
- tf-agents==0.4.0rc0
- tf version 2.1.0
- Nvidia GTX 980

One of my colleagues runs on a MacBook pro with no dedicated GPU, and has no issues, so I don't think it is GPU related based on my observation.

The environment I am using is a custom made for the vizdoom RL framework:

```
import os

import cv2
import numpy as np
from tf_agents.environments import py_environment, utils
from tf_agents.specs import array_spec
from tf_agents.trajectories import time_step
from vizdoom import DoomGame, Mode


class DoomEnvironmentBasic(py_environment.PyEnvironment):

    def get_info(self):
        pass

    def __init__(self):
        super().__init__()

        self._game = self.configure_doom()
        self._num_actions = self._game.get_available_buttons_size()

        self._action_spec = array_spec.BoundedArraySpec(shape=(), dtype=np.int32, minimum=0,
                                                        maximum=self._num_actions - 1, name='action')
        self._observation_spec = array_spec.BoundedArraySpec(shape=(84, 84, 3), dtype=np.float32, minimum=0, maximum=1,
                                                             name='observation')

    @staticmethod
    def configure_doom(config_name="../Scenarios/basic.cfg"):
        game = DoomGame()
        directory = os.path.dirname(os.path.realpath(__file__))
        game.load_config(os.path.join(directory, config_name))
        game.set_mode(Mode.PLAYER)
        game.init()
        return game

    def action_spec(self):
        return self._action_spec

    def observation_spec(self):
        return self._observation_spec

    def _reset(self):
        self._game.new_episode()
        return time_step.restart(self.get_screen_buffer_preprocessed())

    def _step(self, action):
        if self._game.is_episode_finished():
            # The last action ended the episode. Ignore the current action and start a new episode.
            return self.reset()

        # construct one hot encoded action as required by ViZDoom
        one_hot = [0] * self._num_actions
        one_hot[action] = 1

        # execute action and receive reward
        reward = self._game.make_action(one_hot)

        # return transition depending on game state
        if self._game.is_episode_finished():
            return time_step.termination(self.get_screen_buffer_preprocessed(), reward)
        else:
            return time_step.transition(self.get_screen_buffer_preprocessed(), reward)

    def render(self, mode='rgb_array'):
        """ Return image for rendering. """
        return self.get_screen_buffer_frame()

    def get_screen_buffer_preprocessed(self):
        """
		Preprocess frame for agent by:
		- cutout interesting square part of screen
		- downsample cutout to 84x84 (same as used for atari games)
		- normalize images to interval [0,1]
		"""
        frame = self.get_screen_buffer_frame()
        cutout = frame[10:-10, 30:-30]
        resized = cv2.resize(cutout, (84, 84))
        return np.divide(resized, 255, dtype=np.float32)

    def get_screen_buffer_frame(self):
        """ Get current screen buffer or an empty screen buffer if episode is finished"""
        if self._game.is_episode_finished():
            return np.zeros((120, 160, 3), dtype=np.float32)
        else:
            return self._game.get_state().screen_buffer
```

The train_eval.py is the exact same as your example code for DQN V2 with the exception of using my custom environment.

**Comment by kbanoop** [comment] 2020-05-04 22:17
Thanks for reporting this. I am not sure why the Eval environment was faster than the Train environment before. Do you remember an approximate date when it was faster and by how much? 

Also does this difference between train and eval environments exist only for your environment, or any of the standard environments from TF-Agents that we can reproduce easily?

**Comment by HadiSDev** [comment] 2020-05-05 10:03
Well for my colleagues it has always been fast and still is even after the new update. It only stopped on my PC 2 weeks ago. We started working with TF agents start February. 

To give you an example, I was training on a specific scenario for 100000 steps which takes about 1h to train on, when eval Is running fast, and with excellent results. This is on my colleagues pc's. 

When I run it on my PC (exact same code) it takes about 10 min for 5k steps which is a lot and on top of that the end result is way worse than the results that my colleagues achieved.

Regarding testing it on some environment I tried to do that with tf-agents dqn example, but could not figure out how to actually show the window while training. Do you know how to make the window visible?

**Comment by HadiSDev** [comment] 2020-05-05 18:51
Quick update: 
* I tried in ubuntu is evaluating fast, which is good ofc :dancers: 
* I tried on my laptop which also runs on windows 10 pro, and evaluater is evaluating on the same speed as the trainer

**Comment by tfboyd** [comment] 2021-09-11 01:53
Closing due to age and lack of recent activity. If the issue still exists, please open a new issue and reference this one.

**Closed as completed by tfboyd** 2021-09-11 01:53 UTC
