### ISSUE TITLE
Issue test SAC

### ISSUE THREAD

**Issue by Bhaney44** [tensorflow/agents#62] opened 2019-04-04 12:14 UTC
I have been trying to use tf.agents and tf.nightly for a few days now without any luck. Right now I am trying to implement a SAC model, but the test continues to fail on my machine. The error I am receiving is:

`ValueError: A configurable matching 'tf_agents.policies.actor_policy.ActorPolicy' already exists.`

Above the error is the following syntax:

`File "/anaconda3/lib/python3.7/site-packages/gin/config.py", line 891, in _make_configurable
    raise ValueError(err_str.format(selector))`

Generally, I am not sure what is causing the error. I would sincerely appreciate any help or advice. My ultimate goal is to implement a SAC in the OpenAI [CarRacing environment](https://gym.openai.com/envs/CarRacing-v0/). I was not able to find a way to do that with OpenAI's code and I figured agents may provide a solution to my [issue](https://github.com/openai/gym/issues/1267).

**Comment by oars** [comment] 2019-04-04 15:51
Which test is failing for you? The error is coming from gin-config, somehow the ActorPolicy is being defined twice.

I got the CarRacing Env running on sac/examples/v2/train_eval.py directly. See the required changes:

```
36c36
< from tf_agents.environments import suite_gym
---
> from tf_agents.environments import suite_mujoco
74c74
<     env_name='CarRacing-v0',
---
>     env_name='HalfCheetah-v2',
83c83
<     replay_buffer_capacity=10000,
---
>     replay_buffer_capacity=1000000,
97c97
<     use_tf_functions=False,
---
>     use_tf_functions=True,
130,131c130,131
<     tf_env = tf_py_environment.TFPyEnvironment(suite_gym.load(env_name))
<     eval_tf_env = tf_py_environment.TFPyEnvironment(suite_gym.load(env_name))
---
>     tf_env = tf_py_environment.TFPyEnvironment(suite_mujoco.load(env_name))
>     eval_tf_env = tf_py_environment.TFPyEnvironment(suite_mujoco.load(env_name))
```

I haven't used the Box2D envs before. So far they seem a little finicky.

Couple of notes as you hopefully try to extend this for your specific needs:
  * Note the change to the  `replay_buffer_capacity` If you forget this you'll OOM as it pre-allocates the memory. 
  * The environment only works if it is rendered in the main thread so `use_tf_functions` needs to be disabled. (This makes collection a bit slower :().
  * Similarly I saw an issue if I had more than one instance of the environment, so you'll have to remove the use of the eval_tf_env.
  * The networks used are not configured with any `conv_layers` and the input image is simply being flattened at the moment. You can define your own custom networks, or use the built-in `conv_layer_params`.

I'll close this issue for now as I think this should be sufficient to get you going. Please re-open if there is a specific test that is failing.

Best of luck!

**Closed as completed by oars** 2019-04-04 15:51 UTC

**Comment by Bhaney44** [comment] 2019-04-04 16:23
@oars Oscar, thank you so much for your help. I sincerely appreciate your thoughtful analysis.

**Comment by Bhaney44** [comment] 2019-04-04 16:24
This is the test failing:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import copy
import tensorflow as tf

from tf_agents.agents.sac import sac_agent
from tf_agents.environnments import time_step as ts
from tf_agents.policies.policy_step import PolicyStep
from tf_agents.specs import tensor_spec

class _MockDrstribution(object):
    def __init__(self, action):
        self._action = action
    
    def sample(self):
        return self._action
    
    def log_prob(self, unused_sample):
        return tf.constant(10., shape=[1])
    
class DummyActorPolicy(object):
    def __init__(self, time_step_spec, action_spec, actor_network):
        del time_step_spec
        del actor_network
        single_action_spec = action_spec
        
    def action(self, time_step):
        del time_step
        action = tf.constant(self._action, dtype=tf.float32, shape=[1])
        return PolicyStep(action=action)
    
    def distribution(self, time_step):
        action = self.action(time_step).action
        return PolicyStep(action=_MockDistribution(action))
    
class DummyCriticNet(object):
    
    def copy(self, name=''):
        del name
        return copy.copy(self)
    def __call__(self, inputs, step_type):
        observation, actions = inputs
        del step_type
        actions = tf.cast(tf.nest.flatten(actions)[0], tf.float32)
        
        states = tf.cast(tf.nest.flatten(observation)[0], tf.float32)
        #Biggest state is best state.
        value = tf.reduce_max(input_tensor=states, axis=-1)
        value = tf.reshape(value, [-1])
        
        #Biggest action is best action
        q_value = tf.reduce_max(input_tensor=actions, axis=-1)
        q_value = tf.reshape(q_value, [-1])
        #Biggest state is best state
        return value + q_value, ()
    
class SacAgentTest(tf.test.TestCase):
    def setUp(self):
        super(SacAgentTest. self).setUp()
        tf.compat.v1.enable_resource_variables()
        self._obs_spec = [tensor_spec.TensorSpec([2], tf.float32)]
        self._time_step_spec = ts.time_step_spec(self._obs_spec)
        self._action_spec = tensor_spec.BoundedTensorSpec([1], tf.float32, -1, 1)
        
        
    def testCreateAgent(self):
        sac_agent.SacAgent(
                self._time_step_spec,
                self._action_spec,
                critic_network=DummyCriticNet(),
                actor_network=None,
                actor_optimizer=None,
                critic_optimizer=None,
                alpha_optimizer=None,
                actor_policy_ctor=DummyActorPolicy)
        
    def testCriticLoss(self):
        agent = sac_agent.SacAgent(
                self._time_step_spec,
                self._action_spec,
                critic_network=DummyCriticNet(),
                actor_network=None,
                actor_optimizer=None,
                critic_optimizer=None,
                alpha_optimizer=None,
                actor_policy_ctor=DummyActorPolicy)
        
        
        observations = [tf.constant([[1, 2], [3, 4]], dtype=tf.float32)]
        time_steps = ts.restart(observations)
        actions = tf.constant([5], [6], dtype=tf.float32)
        
        rewards = tf.constant([10, 20], dtype=tf.flaot32)

        discounts = tf.constant([0.9, 0.9], dtype=tf.float32)
        next_observatoins = [tf.constant([[5, 6], [7, 8]], dtype=tf.float32)]
        next_time_steps = ts.transition(next_observations, rewards, discounts)
        
        td_targets = [7.3, 19.1]
        pred_td_targets = [7., 10.]
        
        self.evaluate(tf.compat.v1.global_variables_initializer())
        
        #Expected critic loss has factor of 2, for the two TD3 critics.
        expected_loss = self.evaluate(2 * tf.compat.v1.losses.mean_squared_error(
                tf.constant(td_targets), tf.constant(pred_td_targets)))
        
        loss = agent.critic_loss(
                time_steps,
                actions,
                next_time_steps,
                td_errors_loss_fn=tf.compat.v1.losses.mean_squared_error)
        
        self.evaluate(tf.compat.v1.global_variables_initializer())
        loss_ = self.evaluate(loss)
        self.assertAllClose(loss_, expected_loss)
        
    def testActorLoss(self):
        agent = sac_agent.SacAgent(
                self._time_step_spec,
                self._action_spec,
                critic_network=DummyCriticNet(),
                actor_network=None,
                actor_optimizer=None,
                critic_optimizer=None,
                alpha_optimizer=None,
                actor_policy_ctor=DummyActorPolicy)
        observations = [tf.constant([[1, 2], [3, 4]], dtype=tf.float32)]
        time_steps = ts.restart(observations, batch_size=2)
        
        expected_loss = (2 * 10 - (2+1) - (4+1))/2
        loss = agent.actor_loss(time_steps)
        
        self.evaluate(tf.compat.v1.global_variables_initializer())
        loss_ = self.evaluate(loss)
        self.assertAllClose(loss_, expected_loss)
        
        def testAlphaLoss(self):
            agent = sac_agent.SacAgent(
                    self._time_step_spec,
                    self._action_spec,
                    critic_network=DummyCriticNet(),
                    actor_network=None,
                    actor_optimizer=None,
                    critic_optimizer=None,
                    alpha_optimizer=None,
                    target_entropy=3.0,
                    initial_log_alpha=4.0,
                    actor_policy_ctor=DummyActorPolicy)
            
            observations = [tf.constant([1, 2], [3, 4], dtype=tf.float32)]
            time_steps = ts.restart(observations, batch_size=2)
            
            action_step = agent.policy.action(time_steps)
            
            self.evaluate(tf.compat.v1.global_variables_initializer())
            action_ = self.evaluate(action_step.action)
            self.assertLessEqual(action_, self._action_spec.maximum)
            self.assertGreaterEqual(action_, self._action_spec.minimum)
            
if __name__ == '__main__':
    tf.test.main()
```

**Comment by oars** [comment] 2019-04-04 16:34
Do you have a full traceback of the failure? I am unable to reproduce:

```
>>>python tf_agents/agents/sac/sac_agent_test.py
Running tests under Python 3.7.1: /usr/local/google/home/oars/anaconda3/bin/python
[ RUN      ] SacAgentTest.testActorLoss
W0404 09:33:04.191312 140086015112960 deprecation.py:506] From /tmp/tf-agents/tf_agents/utils/common.py:139: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0404 09:33:04.222187 140086015112960 deprecation.py:323] From /usr/local/google/home/oars/anaconda3/lib/python3.7/contextlib.py:82: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2019-04-04 09:33:04.222409: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-04 09:33:04.255266: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594185000 Hz
2019-04-04 09:33:04.264370: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x564017b06190 executing computations on platform Host. Devices:
2019-04-04 09:33:04.264423: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
[       OK ] SacAgentTest.testActorLoss
[ RUN      ] SacAgentTest.testAlphaLoss
[       OK ] SacAgentTest.testAlphaLoss
[ RUN      ] SacAgentTest.testCreateAgent
[       OK ] SacAgentTest.testCreateAgent
[ RUN      ] SacAgentTest.testCriticLoss
[       OK ] SacAgentTest.testCriticLoss
[ RUN      ] SacAgentTest.testPolicy
[       OK ] SacAgentTest.testPolicy
[ RUN      ] SacAgentTest.test_session
[  SKIPPED ] SacAgentTest.test_session
----------------------------------------------------------------------
Ran 6 tests in 0.368s

OK (skipped=1)
python tf_agents/agents/sac/sac_agent_test.py  2.33s user 4.77s system 303% cpu 2.338 total
```

**Comment by Bhaney44** [comment] 2019-04-04 16:37
```
runfile('/Users/brianhaney/Desktop/Martian Technologies/Agents/SAC_Test.py', wdir='/Users/brianhaney/Desktop/Martian Technologies/Agents')
Reloaded modules: __mp_main__, tf_agents, tf_agents.agents, tf_agents.agents.ddpg, tf_agents.agents.ddpg.ddpg_agent, tf_agents.agents.tf_agent, tf_agents.environments, tf_agents.environments.trajectory, tf_agents.environments.time_step, tf_agents.specs, tf_agents.specs.array_spec, tf_agents.specs.tensor_spec, tf_agents.policies, tf_agents.policies.policy_step, tf_agents.utils, tf_agents.utils.nest_utils, tf_agents.utils.common, tf_agents.distributions, tf_agents.distributions.tanh_bijector_stable, tf_agents.policies.actor_policy, tf_agents.networks, tf_agents.networks.network, tf_agents.policies.tf_policy, tf_agents.policies.ou_noise_policy, tf_agents.utils.eager_utils, tf_agents.agents.dqn, tf_agents.agents.dqn.dqn_agent, tf_agents.policies.boltzmann_policy, tf_agents.policies.epsilon_greedy_policy, tf_agents.policies.greedy_policy, tf_agents.policies.random_tf_policy, tf_agents.policies.q_policy, tf_agents.agents.ppo, tf_agents.agents.ppo.ppo_agent, tf_agents.agents.ppo.ppo_policy, tf_agents.agents.ppo.ppo_utils, tf_agents.specs.distribution_spec, tf_agents.utils.tensor_normalizer, tf_agents.utils.value_ops, tf_agents.agents.reinforce, tf_agents.agents.reinforce.reinforce_agent, tf_agents.agents.sac, tf_agents.agents.sac.sac_agent, tf_agents.agents.td3, tf_agents.agents.td3.td3_agent
Traceback (most recent call last):

  File "<ipython-input-2-cd863b90030b>", line 1, in <module>
    runfile('/Users/brianhaney/Desktop/Martian Technologies/Agents/SAC_Test.py', wdir='/Users/brianhaney/Desktop/Martian Technologies/Agents')

  File "/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/brianhaney/Desktop/Martian Technologies/Agents/SAC_Test.py", line 16, in <module>
    from tf_agents.agents.sac import sac_agent

  File "/Users/brianhaney/.local/lib/python3.7/site-packages/tf_agents/agents/__init__.py", line 17, in <module>
    from tf_agents.agents.ddpg.ddpg_agent import DdpgAgent

  File "/Users/brianhaney/.local/lib/python3.7/site-packages/tf_agents/agents/ddpg/ddpg_agent.py", line 32, in <module>
    from tf_agents.policies import actor_policy

  File "/Users/brianhaney/.local/lib/python3.7/site-packages/tf_agents/policies/actor_policy.py", line 38, in <module>
    class ActorPolicy(tf_policy.Base):

  File "/anaconda3/lib/python3.7/site-packages/gin/config.py", line 1129, in configurable
    return perform_decoration(decoration_target)

  File "/anaconda3/lib/python3.7/site-packages/gin/config.py", line 1126, in perform_decoration
    return _make_configurable(fn_or_cls, name, module, whitelist, blacklist)

  File "/anaconda3/lib/python3.7/site-packages/gin/config.py", line 891, in _make_configurable
    raise ValueError(err_str.format(selector))

ValueError: A configurable matching 'tf_agents.policies.actor_policy.ActorPolicy' already exists.
```

**Comment by oars** [comment] 2019-04-04 16:42
How are you running these tests? The issue is due to modules being reloaded which we do not do in our regular tests `python setup.py test`.

To allow that to happen, you need to set: `gin.enter_interactive_mode()`

**Comment by Bhaney44** [comment] 2019-04-04 16:46
I am running the tests in [Spyder](https://www.spyder-ide.org/). What do you mean by:

 "set: set: `gin.enter_interactive_mode()`"?

Big picture issue would be my lack of understanding of how the different files, scripts, and information are organized on my machine. To what are the modules being reloaded into?

**Comment by Bhaney44** [comment] 2019-04-04 16:47
Thanks again for your time and patience. I am greatly appreciative.

**Comment by oars** [comment] 2019-04-04 16:55
I'm not sure how the test runner for Spyder works, but it is forcing a `reload` of modules which is not compatible with `gin`. 

> ... To what are the modules being reloaded into?
You can learn more about how modules work and what reload means in this context by looking at: https://docs.python.org/3/library/imp.html

You can add the line `gin.enter_interactive_mode()`  to allow reloading of modules in `gin`. You'll need to do so in some top level file. Possibly adding `import gin;gin.enter_interactive_mode()` in `tf_agents.__init__.py` could do the trick for you.

**Comment by Bhaney44** [comment] 2019-04-04 16:56
I'm going to grind on this problem until I solve it. Thanks again, Oscar.

**Comment by Bhaney44** [comment] 2019-04-04 18:08
@oars 

Could you please explain this code you proposed?

```
36c36
< from tf_agents.environments import suite_gym
---
> from tf_agents.environments import suite_mujoco
74c74
<     env_name='CarRacing-v0',
---
>     env_name='HalfCheetah-v2',
83c83
<     replay_buffer_capacity=10000,
---
>     replay_buffer_capacity=1000000,
97c97
<     use_tf_functions=False,
---
>     use_tf_functions=True,
130,131c130,131
<     tf_env = tf_py_environment.TFPyEnvironment(suite_gym.load(env_name))
<     eval_tf_env = tf_py_environment.TFPyEnvironment(suite_gym.load(env_name))
---
>     tf_env = tf_py_environment.TFPyEnvironment(suite_mujoco.load(env_name))
>     eval_tf_env = tf_py_environment.TFPyEnvironment(suite_mujoco.load(env_name))
```

Questions:

1. Where is this code? I am going back and forth trying to run this from the command line and Spyder.  Generally, I do not understand how all of these files fit together. So, when you say required changes I do not know how to find or locate what needs to be changed.

2. What does XcX mean? You write variable numbers for the changes, but I do not understand what the numbers represent. For example, 97c97 and 74c74. 

Thanks again for your help. I appreciate your patience.

**Comment by oars** [comment] 2019-04-04 18:23
That represents changes to the code in: `tf_agents/agents/sac/examples/v2/train_eval.py`.

Search for diff syntax to learn more on this, but the gist is that line 36 was changed. One file has `suite_mujoco` the other `... suite_gym` I realize now that I ordered the diff backwards, but the main idea is still there.
