### ISSUE TITLE
ValueRnnNetwork added extra dimention when input does not have time dimension

### ISSUE THREAD

**Issue by emailweixu** [tensorflow/agents#87] opened 2019-04-23 20:39 UTC
In tf_agents.networks.value_rnn_network.ValueRnnNetwork.call(), if `observation` does not have time dimension, it is expanded one more dimension for time at
https://github.com/tensorflow/agents/blob/82317735484b99f8bcb6ec7cb99d1e73f058ca55/tf_agents/networks/value_rnn_network.py#L153-L158

And the `value` just before the following line is a flattened version. Then it's unflattened by the following line to a shape with an extra time dimension:
https://github.com/tensorflow/agents/blob/82317735484b99f8bcb6ec7cb99d1e73f058ca55/tf_agents/networks/value_rnn_network.py#L184

Shouldn't the correct behavior be that if the input observation does not have time dimension, the output should not either?

**Comment by oars** [comment] 2019-04-24 15:46
Yeah, that seems like a bug to me. Thanks for the report!

**Comment by tfboyd** [comment] 2020-02-13 22:34
There has been a lot of refactoring.  While I did not test it, looking at the code I believe the issue is fixed by this line:
https://github.com/tensorflow/agents/blob/master/tf_agents/networks/lstm_encoding_network.py#L205

This PR to fix this issue was also from a long time ago.  We are trying to do a much better job of handling PRs and int he past two weeks have been much more responsive.  We hope to keep it up and sorry we let this hang, this was 100% a fix; and thank you for pointing it out.

**Closed as completed by tfboyd** 2020-02-13 22:34 UTC
Labels: type:bug
