### ISSUE TITLE
summary() outputs "QNetwork object has no attribute _check_trainable_weights_consistency"

### ISSUE THREAD

**Issue by ageron** [tensorflow/agents#117] opened 2019-05-24 01:35 UTC
The `QNetwork` class inherits from Keras's `Network` class, so I should be able to display the `summary()`, but I get an exception (see stacktrace below). Here's a small program to reproduce the error:

```python
import numpy as np
from tensorflow import keras
import tensorflow as tf
from tf_agents.networks.q_network import QNetwork
from tf_agents.specs import TensorSpec, BoundedTensorSpec
from tf_agents.agents.dqn.dqn_agent import DqnAgent
from tf_agents.trajectories.time_step import TimeStep

dqn = QNetwork(
    BoundedTensorSpec(shape=[2], dtype=tf.float32, minimum=0, maximum=1),
    BoundedTensorSpec(shape=[], dtype=tf.int32, minimum=0, maximum=3),
    fc_layer_params=[32])

optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=2.5e-4)
train_step_counter = tf.Variable(0)
agent = DqnAgent(
    TimeStep(
        step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
        reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'),
        discount=BoundedTensorSpec(
            shape=(), dtype=tf.float32, name='discount',
            minimum=np.array(0., dtype=np.float32),
            maximum=np.array(1., dtype=np.float32)),
        observation=BoundedTensorSpec(shape=[2], dtype=tf.float32,
            name='observation', minimum=np.array(0., dtype=np.float32),
            maximum=np.array(1., dtype=np.float32))),
    BoundedTensorSpec(shape=[], dtype=tf.int32, minimum=0, maximum=3),
    q_network=dqn,
    optimizer=optimizer,
    td_errors_loss_fn=keras.losses.Huber(reduction="none"),
    train_step_counter=train_step_counter)
agent.initialize()

dqn.summary()
```

Produces this output:

```python
Model: "QNetwork"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
EncodingNetwork (EncodingNet multiple                  96
_________________________________________________________________
dense (Dense)                multiple                  132
=================================================================
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-60f4544e3c3a> in <module>
     32 agent.initialize()
     33
---> 34 dqn.summary()

~/miniconda3/envs/testagents/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py in summary(self, line_length, positions, print_fn)
   1510                               line_length=line_length,
   1511                               positions=positions,
-> 1512                               print_fn=print_fn)
   1513
   1514   def _validate_graph_inputs_and_outputs(self):

~/miniconda3/envs/testagents/lib/python3.6/site-packages/tensorflow/python/keras/utils/layer_utils.py in print_summary(model, line_length, positions, print_fn)
    228       print_fn('_' * line_length)
    229
--> 230   model._check_trainable_weights_consistency()
    231   if hasattr(model, '_collected_trainable_weights'):
    232     trainable_count = count_params(model._collected_trainable_weights)

AttributeError: 'QNetwork' object has no attribute '_check_trainable_weights_consistency'
```

**Comment by seungjaeryanlee** [comment] 2019-05-28 07:59
Just commenting to hope clarify the issue.

In Keras, `_check_trainable_weights_consistency` is defined in [Keras's `Model` class](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L1959), which inherits Keras's `Network` class. The error occurs because `QNetwork` inherits Keras's `Network`class and not `Model`.

**Comment by egonina** [comment] 2019-05-28 16:00
you're right, I'm able to reproduce this bug with your code snippet. It looks like the only test for keras  network summary() is actually called on a keras model (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/network_test.py#L638) and not on a keras network. Looks like a keras bug to me, cc @oars who is more familiar with the use of keras in our code, should we file an issue with keras? thanks!

**Comment by oars** [comment] 2019-05-28 16:18
Thanks for the report, and thanks @seungjaeryanlee for the investigation. Following up with the Keras team.

**Comment by tfboyd** [comment] 2019-10-30 18:53
Another fix is to just implement the method in QNetwork and do nothing, which is what keras.Model does.  I will assign this to myself once I am added to the repo and see if @oars finds my solution or something similar acceptable.  I also like printing the summary.  :-)

**Comment by tfboyd** [comment] 2019-10-31 19:30
Fix is in progress  ETA ~5 days.  05-NOV.  Will update when submitted.

**Comment by tfboyd** [comment] 2019-11-04 19:06
Fixed  https://github.com/tensorflow/agents/commit/b3e962248f25ad33aea787a89947df3cabc84278

**Closed as completed by tfboyd** 2019-11-04 19:06 UTC
